novoda/download-manager

README.md
demo/build.gradle
library/build.gradle
library/src/main/AndroidManifest.xml
library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java

Fixes #3 
Now if a client wishes to use Download-Manager they have to declare `manifestPlaceholders = [downloadAuthority: "WATEVER_U_WANT"]` and then this will be used as the name of the content provider authority allowing, multiple apps using this library to be installed at the same time.

force one content provider per install

---

library/src/main/java/com/novoda/downloadmanager/lib/Constants.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadDrmHelper.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadNotifier.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadScanner.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/Downloads.java
library/src/main/java/com/novoda/downloadmanager/lib/Helpers.java
library/src/main/java/com/novoda/downloadmanager/lib/NetworkMeter.java
library/src/main/java/com/novoda/downloadmanager/lib/OpenHelper.java
library/src/main/java/com/novoda/downloadmanager/lib/Query.java
library/src/main/java/com/novoda/downloadmanager/lib/Request.java

This PR reduces the scope of the DownloadManger API, as a lot of classes were publicly accessible which they probably shouldn't have been. This reduces their scope to package-scope. Furthermore, methods which were annotated with `@hide` have also had their scope reduced. 
Some code which is accessible only to system apps, or hidden because the original DownloadManager API wasn't finished (!) has been removed.
| Before | After |
| --- | --- |
| ![screen shot 2015-05-13 at 10 50 19](https://cloud.githubusercontent.com/assets/666285/7608816/0e2f240e-f965-11e4-937d-2c1512b84553.png) | ![screen shot 2015-05-13 at 11 41 14](https://cloud.githubusercontent.com/assets/666285/7608829/256ef388-f965-11e4-851b-0260cdf9a65b.png) |

Reducing scope of DownloadManager API

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/Downloads.java

Removes references to "scuba" in the code. This was used as a unique identifier to avoid collisions with `android.app.DownloadManager` in MUBI.

Scuba cleanup

---

demo/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java

Toggles off the verbose logging that we should not be doing.
Logs are off by default for any new versions of the library.
This is done with a static flag (it is in a content provider so I cannot pass it the flag through construction). This implies you only have one instance of DownloadManager if you have two one with logging on and one with logging off the latest created will win.
Alternative would be to check the system property for verbose logging and then only log in those situtations? This still would mean 2 instances of the manager would favor the latest flag, so no gain...
Formatted some of the code so the diff is a bit bigger.
This fixes #19 which will give performance improvements for all clients.

Remove Logging and add extensible public api

---

demo/build.gradle
demo/src/main/AndroidManifest.xml
demo/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
demo/src/main/res/values/integers.xml
demo/src/parallel/res/values/integers.xml
library/src/main/java/com/novoda/downloadmanager/lib/DownloadExecutorFactory.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java

Adds the possibility to configure the max concurrent downloads. As the download manager is a per app basis component, in order to specify the max number the client would have to include the following `meta-data` in its `AndroidManifest.xml` rather than relying on the `DownloadManagerBuilder`:
```xml
<meta-data
android:name="com.novoda.downloadmanager.MaxConcurrentDownloads"
android:value="1" />
```
If the `meta-data` tag is not present, the download manager will default to a maximum of 5 concurrent downloads maintaining the old behaviour. 
The specified value basically configures the `maximumPoolSize` of the `ThreadPoolExecutor`.  
_Note: The demo project now has 2 flavours - serial and parallel - in order to demo the usage of both cases_

Configurable max concurrent downloads

---

library/src/main/java/com/novoda/downloadmanager/lib/OkHttpNotificationImageRetriever.java

Currently the image for a download notification is fetched from the network every time the notification is updated. This causes memory usage to grow rapidly which causes GC to happen more often. It also wastes network bandwidth.
The retriever will now cache the latest Bitmap and return it without a network request when the same URL is requested.
Before | After
---|---

Cache requested bitmap for notifications

---

gradle/wrapper/gradle-wrapper.properties
library/build.gradle
library/src/main/java/com/novoda/downloadmanager/lib/ConcurrentDownloadsLimitProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadExecutorFactory.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/test/java/com/novoda/downloadmanager/lib/ConcurrentDownloadsLimitProviderTest.java
library/src/test/java/com/novoda/downloadmanager/lib/DownloadExecutorFactoryTest.java

* Tests creation of the `ThreadPoolExecutor` to make sure that the thread pool is the correct size as this controls the number of concurrent downloads allowed.
* Updates build tools and Gradle versions.
* Adds JUnit, Mockito and Fest for testing.

Add tests around configuring concurrent downloads limit

---

demo_parallel/src/main/java/com/novoda/downloadmanager/demo/parallel/MainActivity.java
demo_serial/src/main/java/com/novoda/downloadmanager/demo/serial/MainActivity.java
library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/GlobalState.java
library/src/main/java/com/novoda/downloadmanager/lib/Request.java

Enforces passing a Context via the DM Builder
This means we don't need to pass in a Context to create a Request
Note this is a BREAKING CHANGE! since we've changed the API but it is an improvement since it didn't make sense having to pass in the Context for each Request

Enforces passing a Context via the DM Builder

---

demo_parallel/src/main/java/com/novoda/downloadmanager/demo/parallel/MainActivity.java
demo_serial/src/main/java/com/novoda/downloadmanager/demo/serial/MainActivity.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java

Downloads were being set to `RUNNING` before they were actually ran by the Executor service, this PR now applies the RUNNING status in the `runnable run()` instead of when the task is submitted.
Submitted tasks are set to `PENDING` no gif since the demo project isn't loading for me (or @Electryc even on master) but works fine in our external project, gotta have faith!
**SIDEEFFECT -** 
this causes the serialised notification to no longer be stacked, no affect on parallel (this behaviour matches play music)

31 bug/serialised downloads dont show as queued

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadClientReadyChecker.java

It is of relevance for the client to be aware of that the method `isAllowedToDownload` will be called from a background thread.
This task adds a Javadoc in order to document this fact to the public API

Adds javadoc for documenting the method isAllowedToDownload

---

library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java

We have a new feature that allows a client to tell the DownloadManager if a download can proceed or not.
This PR adds that information to the public DownloadManagerBuilder

Adds documentation for the new DownloadClientReadyChecker functionality

---

demo_parallel/src/main/java/com/novoda/downloadmanager/demo/parallel/MainActivity.java
demo_serial/src/main/java/com/novoda/downloadmanager/demo/serial/MainActivity.java
library/src/main/java/com/novoda/downloadmanager/lib/ActiveBatch.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchStatusUpdater.java
library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadBatch.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadNotifier.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadReceiver.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/Downloads.java
library/src/main/java/com/novoda/downloadmanager/lib/Helpers.java
library/src/main/java/com/novoda/downloadmanager/lib/NotificationVisibility.java
library/src/main/java/com/novoda/downloadmanager/lib/Request.java
library/src/main/java/com/novoda/downloadmanager/lib/RequestBatch.java
library/src/main/java/com/novoda/downloadmanager/lib/SizeLimitActivity.java

* Rework the `DownloadService`, `DownloadThread`, `DownloadReceiver` and `DownloadNotifier` to operate in terms of batches, instead of individual downloads
* Adds status and notification visibility columns to the Batch table
* Update the status of the batch when the status of a corresponding download changes
* Fix downloads not being marked as active when they begin downloading: https://github.com/novoda/download-manager/commit/8af7cc38d088581fa401fd527d978298a45b0d94
* Handles cancellation correctly for an entire batch of downloads
* Stops retrying on 404 errors
Next steps for a new PR:
* Removed unused columns on the `Request` table
* Allow querying for batch status from the API
* Fix `OpenHelper` trying to use system DownloadManager as our DownloadManager
* Test with …

Handle batch failures, cancellation and notifications

---

README.md
RELEASE-NOTES.md
demo_parallel/build.gradle
demo_parallel/src/main/AndroidManifest.xml
demo_parallel/src/main/res/values/strings.xml
demo_serial/build.gradle
library/build.gradle
library/src/main/java/com/novoda/downloadmanager/lib/DatabaseFilenameProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java
library/src/test/java/com/novoda/downloadmanager/lib/DatabaseFilenameProviderTest.java

A project upon which I'm working is already using a database with the filename `downloads.db`. For legacy reasons it is not possible to change this so it would be useful if `download-manager` could be configured to use an alternate database filename.
Adds the ability to override the database filename via an AndroidManifest metadata value in a similar fashion to the existing `MaxConcurrentDownloads` implementation. This provides me with a simple way to overcome my specific problem while offering additional functionality for power users. All this without actually changing the default, out-of-the-box behaviour.
I also fixed 3 (albeit simple) lint warnings.

Allow custom database filename

---

library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java

Filtering on the extras column allows us to use `setExtra()` on a `Request` to tag a request and make it easier to retrieve it from a batch later on.
**Example**
```java
Request request = new Request(thumbnailUri);
request.setExtra("thumbnail");
downloadManager.enqueue(request);
// Later
Query query = new Query().setFilterByBatchId(batchId)
.setFilterByExtras("thumbnail");
downloadManager.query(query);
```

Add extras column to DownloadsByBatch view so we can filter on it

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java

When there are several queued items to be downloaded, the following bug occurs
Force the `DownloadClientReadyChecker` to return false under some circumstances, for example when there is no Wi-Fi
- 2 queued items
- 1 item is downloading, 1 item is queued
- Switch off Wi-Fi
Expected:
- 2 items moved to queued
- No notification
Result:
- Previous downloading item moves to queued
- Previous queued item moves to downloading
- Notification stays in place
- The submitted thread for a particular download now does a check against the `DownloadClientReadyChecker`
- The `DownloadService` is stopped only if there are no any active download threads
Paired with @ronocod

Fix bug wrong download status when is not ready to download

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchStatusRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java

This PR replaces a full loop over all the rows retrieved by a query by one single query that does all the sums in the query itself

Optimisation Fix - Get full batch size in one query

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchStatusRepository.java

This PR checks for any `status_error` while gathering the values directly from the database and aborts the execution if one is found.
This improvement prevents unnecessary further data gathering from the content provider and removes completely a full loop through all the values gathered looking for a `status_error`

Removes unnecessary full loop

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java

Because the logical order was changed this meant clients had access to the already successfully downloaded files and could check rules against them. https://github.com/novoda/download-manager/pull/45/files#diff-68db38a7048316539cb0931793be1808R447 Now we reverted back to the download manager doing the first check to stop this crazyness.

Fixes too many callbacks about the rules for already downloaded files

---

demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/Download.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/DownloadAdapter.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/MainActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/QueryForDownloadsAsyncTask.java
demo-extended/src/main/res/layout/list_item_download.xml
demo-extended/src/main/res/values/strings.xml
library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/Downloads.java

Adds marking batches for deletion to the public API.
The `DownloadService` will find batches that have been marked for deletion and:
* delete the files for their downloads
* delete the DB entries for those downloads
* delete the DB entries for the batches themselves
Before Deletion | After Deletion
---|---

Add ability to delete batches

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadNotifier.java

This PR replaces the following data structures:
- Batches from `HashSet` to `ArrayList` because the insertion on an ArrayList is faster and there is no usage of any of the HashSet specific implementation advantatges
- mActiveNotifs and cluster from `HashMap` to `SimpleArrayMap` because the length of the items added to the maps are not too extensive, and so the optimised SimpleArrayMap is recommended (further detail at https://medium.com/google-developers/developing-for-android-ii-bb9a51f8c8b9)
Comment at https://github.com/novoda/download-manager/compare/Replace-data-structures?expand=1#diff-ee31e2ad08f5842e25b4b0175c130855L181 solved

Replace data structures for more appropriate ones

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java

When deleting a particular batch, only the first download from the batch is actually deleted
We have spotted the bug on which the query for getting all the downloads was actually getting only the first download
- We query all the downloads for the deletion process
- We reuse query methods in order to minimise duplication and reuse code
- Split query from deletion in order to make the code simpler to understand
Paired with @ronocod

Fix batch deletion bug

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/Query.java
library/src/test/java/com/novoda/downloadmanager/lib/QueryTest.java

Fixes the error:
```
E/SQLiteLog﹕ (1) near ")": syntax error
```
when no batch IDs have been provided to a `Query`.
Also simplifies the SQL generation and adds test around this functionality.

Fix error when no batch ID is provided for the Query filter

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadNotifier.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/NotificationDisplayer.java
library/src/test/java/com/novoda/downloadmanager/lib/DownloadNotifierTest.java

There is a `NullPointerException` at executing `tag.hashCode()` when `removeStaleTagsThatWereNotRenewed(...)`
- The deletion of an item through a manual iteration must be done in reverse order
- We have extracted the code related to displaying the notifications
- We have added tests around removing the staled notifications
Paired with @amlcurran

Fix wrong item deletion looping through a list of items

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java

This PR amends the comments at https://github.com/novoda/download-manager/pull/62#discussion_r33934601
- Use `selection` and `selectionArgs` instead of a constant value
- Project only the column that we need

Revert constant for query selection and project only the column needed

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/test/java/com/novoda/downloadmanager/lib/BatchRepositoryTest.java

We weren't checking that the first batch in the retrieved list matched the dowload info batch id, this caused the `isAllowedToDownload` to always be called with the first downloaded batch!
Fixed by enforcing the batch ids to be matched instead of just using the first list entry

Incorrect batch id passed to the rule checker

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java

Forces the download batch to be fully sized up before hitting the `isAllowedToDownload()` rules and download thread
Fixes `isAllowedToDownload` being called with -1 total size
Removes the cached `mDownloads`, they were being used as a back up to when the content provider failed(?!) **BUT** if the content provider failed we wouldn't be able to read from the map anyways because we were calling `contentResolver.query().getLong(id)`... ! Removing them super simplified the download flow and due to the reuse of the download batches and download infos, we no longer have to query on each iteration of the loop, performance increased!
Logs taken at the start and end of `updateLocked()` in the `DownloadService`
Before 119, 118, 87, 91, 113, 139, 63, 61, 62, 65 average = **91.8ms**
After 75, 6, 4, 5, …

Calculate entire batch size in one go

---

demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/Download.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/QueryForDownloadsAsyncTask.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/pause_resume/PauseResumeActivity.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/Query.java
library/src/test/java/com/novoda/downloadmanager/lib/QueryTest.java

This PR adds the ability to sort downloads by a couple of previously-unexposed sorts, and also by a new one. The new one is sort by "liveness" (better naming welcome) which basically sorts the downloads by their status in this order: _running, queued, other statuses, paused, failed, complete_. 
| Before | After |
| --- | --- |
| ![not-sorted](https://cloud.githubusercontent.com/assets/666285/8550592/612a62c4-24c9-11e5-9b60-83cad73bd4dd.gif) | ![sort-queries](https://cloud.githubusercontent.com/assets/666285/8550597/67488b86-24c9-11e5-812e-b647dffb2072.gif) |

Sort queries

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/Downloads.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/FileDownloadInfo.java

#75 removed the in memory maps of downloads but also had the side effect of no longer using the mutable `DownloadInfos` contained within.
The `DownloadThread` was making use of this mutable state via the `control status` which was being updated via the `DownloadService`, this was no longer the case.
The `DownloadInfo` also retained the thread instance to be able to tell if it was complete, this has been replaced with a column status `SUBMITTED`. THE DB IS THE TRUTH
This PR adds download querying within the main download loop to check for control changes.
- Also simplifying the `isActive` logic by returning less booleans from methods which do more than one thing (looking at you `startDownloadIfReady`)

Fix download info state

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java

We found that isAllowedToDownload was being called for all queued and running downloads, on EVERY download table change. It kind of made sense for running downloads but wasn't really necessary...
This PR forces the check to only occur if a download hasn't been set to submitted or in progress before checking if that download is "ready to download"

Less isAllowToDownload callbacks

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/FileDownloadInfo.java

We've noticed that the current size for the batches was not computed anymore. This is due to the fact that `batchRepository.updateCurrentSize(downloadInfo.getBatchId())` was executed only when there are no total bytes on the batch (notice the `if`) which was wrong - the current size should always be computed. 
Pulls updating the current size out of the check and replaces the hardcoded check with a method on `downloadInfo`.

Fix current size for batches

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/FileDownloadInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/SizeLimitActivity.java

refactoring based around #89 only check against the current download (this PR is raised against it, and could be merged in)
simplifies the `FileDownloadInfo`, removes lots of unused dependencies and inlines a few of the methods into their only usage, the `DownloadThread`, ready to be extracted into their own classes!
**API CHANGE!** moves the `FileDownloadInfo.EXTRA_EXTRA` to `DownloadManager.EXTRA_EXTRA`

Simplifying download info

---

demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/Download.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/Batch.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/ShowBatchesActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/delete/DeleteActivity.java
demo-extended/src/main/res/layout/activity_show_batches.xml
demo-extended/src/main/res/values/strings.xml
demo-simple/src/main/java/com/novoda/downloadmanager/demo/simple/Download.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchQuery.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadStatus.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/Query.java
library/src/test/java/com/novoda/downloadmanager/lib/BatchQueryTest.java
library/src/test/java/com/novoda/downloadmanager/lib/DownloadStatusTest.java

We need to bubble up immediately when a batch is marked for deletion.
The current implementation marks a flag in a table that doesn't affect the current status of a downloads
As soon as a batch is marked for deletion, the batch status immediately changes to a new status `deleting`. This status happens in the same table that any other statuses and so all listeners monitoring the status of a download will be immediately notified.
Previous | Now
--- | ---
Notice that the demo `DeleteActivity` has changed the way that listens for updates in the database. The previous implementation failed to refresh a second event if that one is faster than the `lastQueryTimestamp`, here's an example of the previous implementation (the gif old has this fixed in order to show updates):

Add deleting status

---

library/src/main/java/com/novoda/downloadmanager/lib/NotificationDisplayer.java

we should always set a notification icon
https://github.com/shorelinedev/aosp_frameworks_base/blob/master/services/java/com/android/server/NotificationManagerService.java#L1842
```kotlin
07-13 12:03:25.501     470-2496/system_process E/NotificationService﹕ WARNING: In a future release this will crash the app: com.novoda.demo
07-13 12:03:25.533      470-470/system_process E/NotificationService﹕ Not posting notification with icon==0: Notification(pri=0 contentView=com.novoda.demo/0x1090082 vibrate=null sound=null defaults=0x0 flags=0x0 kind=[null])
```

Fix log warning about no icon being set

---

library/src/main/java/com/novoda/downloadmanager/lib/Query.java
library/src/test/java/com/novoda/downloadmanager/lib/QueryTest.java

**breaking API change** need to remember this when we write the changelog & release
Fixes https://github.com/novoda/download-manager/pull/88#issuecomment-120435573
Now that we have an extra data column where clients can pass whatever they want through the download manager. It is right to also add the ability to query on this field.
Did some boyscouting and added 2 more tests and some clean up.

Update query ability - can now query on Extra Data

---

library/build.gradle

This PR adds a value for downloadAuthority to be used in integration test.
Currently, there are no test in `androidTest` but the missing value can make `gradle sync` fail in Android Studio when the test artifact is set to Android instrumentation test.

98/Fix processDebugAndroidTest

---

demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/pause_resume/PauseResumeActivity.java
library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadContract.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/FileDownloadInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/Request.java

Adds a flag which allows a download to be resumed regardless of whether the server has returned an [Etag header](https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers#content-based) or not

Allow any resume

---

code-quality/rules/pmd/ruleset.xml
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/Query.java
library/src/test/java/com/novoda/downloadmanager/lib/QueryTest.java

- We have found out that `DownloadContract.Downloads.COLUMN_NOTIFICATION_EXTRAS` was not part of the columns bundled up in the Cursor for a download query, so I have added it. 
- Also, in case of filtering by multiple notification extras, we should not attempt if the passed in array is empty as well as the `OR`s done between the statements should be inclosed in brackets. 
- After we enqueue a `RequestBatch` along with its `Requests` we have to notify that the batch has changed. This should be done because conceptually the batch is available only when its downloads are in the database as well, but because we cannot insert the batch at the end (i.e. after we insert the `Requests`) due to the fact that we need the `batch_id` for the requests, we have to manually notify after the whole …

Notify batch modified after all downloads

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadContract.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java

Removes the updating of the total size and current size for batches, instead using a view to calculate the size on demand. 
The public API is still the same, the demo apps work as before.
Running time of `updateLocked()` before and after:
```
BEFORE
173ms
168ms
206ms
247ms
145ms
178ms
169ms
321ms
188ms
150ms
182ms
266ms
173ms
152ms
212ms
AFTER
78ms
112ms
143ms
78ms
82ms
74ms
76ms
82ms
88ms
88ms
79ms
105ms
80ms
```

Batch sizes view

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/FileDownloadInfo.java

I've noticed an excessive number of invocations to the creation of the `FileDownloadInfo` object.
This is the analysis:
- Creation of the `FileDownloadInfo` object have a class level `synchronise`, along with an extra database query for the headers
- `FileDownloadInfo` is fully created but only the values `status` and `control` are used, the rest of the values are completely useless for this trace
- The `status` and `control` are queried at the method `checkPausedOrCreated` and invokated at `DownloadThread.transferData`.
So everytime that there is a transfer data, we call checkPausedOrCreated that creates a full FileDownloadInfo object in order to just check the status and the control.
I've created a slimmed down version that only creates an object with the `status` and `control` fields, …

Simplify query status control

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadContract.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/test/java/com/novoda/downloadmanager/lib/BatchRepositoryTest.java
library/src/test/java/com/novoda/downloadmanager/lib/QueryTest.java

Adds a new column that keeps the timestamp of the last modification made to a batch, that is when the status of a batch was last modified.
We also renamed the LAST_MODIFIED column from Downloads so that we can use the same name as the one in Batches.

Batch with timestamp

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadBatch.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadReadyChecker.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java

We have seen how a batch moves to the `queued` status for no reason in the middle of a download
[PENDING TO BE UPDATED AFTER LASTS MODIFICATIONS]
After investigating the code, this is what is happening:
- The `downloadService` has the handler that executes the downloads and processes statuses. Inside the handler there is a method called `updateLocked` that returns a boolean and is assigned to a `isActive` local variable
- When `isActive` is false, the `downloadService` shuts down
- `updateLocked` checks if a client is ready for a download or if the downloadmanager itself is ready for a download.
- The check for `isDownloadManagerReadyToDownload` returns false and shuts down the `downloadService` when the status of the `FileDownloadInfo` is `SUCCESS`
The solution has been to add the status …

Fix download goes to queued

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadDeleter.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/FileDownloadInfo.java

Removes all the setters from `FileDownloadInfo`! Next step, all final fields. 
- Removes unused `cleanUpStaleDownloadsThatDisappeared` which was part of the in memory downloads syncing which is no longer needed
- Makes use of the `state.totalSize` instead of setting and refetching the the total download size from the `FileDownloadInfo`

FileDownloadInfo setter removal

---

demo-extended/build.gradle
demo-simple/build.gradle
library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java

Allows a batch which is half way through being paused to be considered paused, rather than flicking between running and paused as it currently does.
This also updates appcompat because of Lint errors

Give the paused state a higher priority

---

demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchDownloadsActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchesActivity.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/test/java/com/novoda/downloadmanager/lib/BatchStatusTests.java

This PR adds fixes an issue where, when a download in a batch completes, the batch's status would briefly go to "queued", even though from the batch's point of view it is still running.
Also, it looks like the notification doesn't flicker either!
FYI the flicker happens at around 10MB
| Before | After |
| --- | --- |
| ![broken-wobble](https://cloud.githubusercontent.com/assets/666285/8802019/7b79e5a8-2fb6-11e5-9596-705ea7983fc8.gif) | ![fix-wobbly-state](https://cloud.githubusercontent.com/assets/666285/8802022/8194c8d6-2fb6-11e5-8ee6-554a02323c79.gif) |

Fix batch status flickering

---

library/src/main/java/com/novoda/downloadmanager/lib/CheckedWriter.java
library/src/main/java/com/novoda/downloadmanager/lib/Constants.java
library/src/main/java/com/novoda/downloadmanager/lib/DataTransferer.java
library/src/main/java/com/novoda/downloadmanager/lib/DataWriter.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/NotifierWriter.java
library/src/main/java/com/novoda/downloadmanager/lib/RegularDataTransferer.java
library/src/main/java/com/novoda/downloadmanager/lib/SpaceVerifier.java
library/src/main/java/com/novoda/downloadmanager/lib/StorageSpaceVerifier.java
library/src/main/java/com/novoda/downloadmanager/lib/TarFileTruncator.java
library/src/main/java/com/novoda/downloadmanager/lib/TarTruncator.java
library/src/test/java/com/novoda/downloadmanager/lib/CheckedWriterTest.java
library/src/test/java/com/novoda/downloadmanager/lib/TarFileTruncatorTest.java
library/src/test/java/com/novoda/downloadmanager/lib/TarTruncatorTest.java

This change allows to avoid doing a file replacement during processing
time and thus allows to process files while someone has a read
inputstream open.
This is also cleaning a lot the DownloadThread in the process to allow
that customisation

Tar truncation at download time

---

library/src/main/java/com/novoda/downloadmanager/lib/Clock.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/NotifierWriter.java
library/src/main/java/com/novoda/downloadmanager/lib/RealSystemFacade.java

I've noticed that the GC goes crazy while downloading
At every HTTP byte transfer there is a check for paused or cancelled downloads that leads to a database query. Even though the query is small, is too frequent.
The solution implemented prevents fast queries in series to the database preventing more than one query per second.
This will allow a check of paused or cancelled inside a time frame of 1s that is good enough and reduces dramatically the GC
**Screenshots**
Before | After
--- | ---
**Before small log snipped for GC logs**
```
07-23 11:12:56.819  15125-15183/com.novoda.downloadmanager.demo.extended I/art﹕ Explicit concurrent mark sweep GC freed 107078(5MB) AllocSpace objects, 0(0B) LOS objects, 40% free, 20MB/34MB, paused 557us total 15.386ms
07-23 11:12:57.607 …
```

Avoid smashing the database while transferring bytes

---

demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/DemoApplication.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchDownloadsActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchesActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/delete/DeleteActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/extra_data/ExtraDataActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/pause_resume/PauseResumeActivity.java
library/src/main/java/com/novoda/downloadmanager/lib/ConcurrentDownloadsLimitProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/ContentLengthFetcher.java
library/src/main/java/com/novoda/downloadmanager/lib/DatabaseFilenameProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadDeleter.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadNotifier.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadReceiver.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadScanner.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/FileDownloadInfo.java
library/src/main/java/com/novoda/downloadmanager/lib/GlobalState.java
library/src/main/java/com/novoda/downloadmanager/lib/Helpers.java
library/src/main/java/com/novoda/downloadmanager/lib/IOHelpers.java
library/src/main/java/com/novoda/downloadmanager/lib/RealSystemFacade.java
library/src/main/java/com/novoda/downloadmanager/lib/SizeLimitActivity.java
library/src/main/java/com/novoda/downloadmanager/lib/StorageManager.java
library/src/main/java/com/novoda/downloadmanager/lib/logger/LLog.java

Removes NoTils Logger in favour of one that doesn't query the stacktraces when it logs.
This won't impact performance in production but will contribute to perceived performance in debugging.
The test here was using the advanced demo and pressing "download a batch of items" the screenies show from start to completion.
| before |
| --- |
|![screen shot 2015-07-24 at 15 23 42](https://cloud.githubusercontent.com/assets/655860/8876581/83218b26-3218-11e5-89b8-1e73533fbe36.png)|
| after |
| --- |
|![screen shot 2015-07-24 at 15 21 58](https://cloud.githubusercontent.com/assets/655860/8876587/86d9d3d6-3218-11e5-94da-a6cf1672fe8a.png)|
LLog == Library Log

simplifies logging

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/NotifierWriter.java

One of the outcomes of the DownloadManager meeting was about the amount of garbage collection (potentially) being caused by data transfer loop.
---------
This PR removes the content values and ControlStatus.Reader object creation from deep within the transfer data while(true) loop to reduce unnecessary garbage collection

Reducing transfer object creation

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/FileDownloadInfo.java

More transfer data while(true) loop allocation reductions!
Forces the `ControlStatus.Reader` to be constructed with all its query dependencies rather than creating them each time a query is requested.
This means we don't have to create the uri or projection upon querying
Allocations for a single GC from a fresh install
| Before | After
| --- | --- 
|<img width="644" alt="download-before" src="https://cloud.githubusercontent.com/assets/1848238/8889090/6ddde110-32c2-11e5-920d-493a436004b7.png">|<img width="622" alt="download-after" src="https://cloud.githubusercontent.com/assets/1848238/8889093/7da05c4a-32c2-11e5-9c1d-50f4046b3fbe.png">
Total allocations before **81,034** After **80,375**

Reducing control reader query method allocations

---

demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/pause_resume/PauseResumeActivity.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchPauseResumeController.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadStatus.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java
library/src/test/java/com/novoda/downloadmanager/lib/BatchStatusTests.java

I have noticed that a queued download can be paused and that causes the following bug:
- Proceed downloading two batches, the first one is running, the second one is queued
- Click to pause a queued batch, queued status stays in place
- Click to pause the running batch
- The queued batch does not start as it has been paused, but as is queued it should start
We should only be able to pause running batches, and resume paused ones
Before | After
--- | ---

Prevent pause a non running task and prevent resume a non paused task

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchQuery.java
library/src/test/java/com/novoda/downloadmanager/lib/BatchQueryTest.java

The status `QUEUED_DUE_CLIENT_RESTRICTIONS` was missing from the BatchQuery filter type `paused``
This PR adds the missing status along with the current ones
- PAUSED_BY_APP
- WAITING_TO_RETRY
- WAITING_FOR_NETWORK
- QUEUED_FOR_WIFI

Adds missing status as a paused batch query filter

---

demo-extended/build.gradle
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/QueryForDownloadsAsyncTask.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchDownloadsActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchDownloadsAdapter.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchesActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchesAdapter.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/delete/DeleteActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/delete/DeleteAdapter.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/extra_data/ExtraDataActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/extra_data/ExtraDataAdapter.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/pause_resume/PauseResumeActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/pause_resume/PauseResumeAdapter.java
demo-extended/src/main/res/layout/activity_batches.xml
demo-extended/src/main/res/layout/activity_delete.xml
demo-extended/src/main/res/layout/activity_extra_data.xml
demo-extended/src/main/res/layout/activity_pause_resume.xml
demo-extended/src/main/res/layout/activity_show_batches.xml
demo-simple/build.gradle
demo-simple/src/main/java/com/novoda/downloadmanager/demo/simple/DownloadAdapter.java
demo-simple/src/main/java/com/novoda/downloadmanager/demo/simple/MainActivity.java
demo-simple/src/main/res/layout/activity_main.xml
library/build.gradle

The lists in the demos were using `ListView` without the ViewHolder pattern. This caused higher CPU usage than necessary when updating the lists as all the Views were being recreated on each update.
Rather than just implementing the ViewHolder pattern on the ListView adapters I decided to move all the lists to RecyclerView.
UI is the same as before.

Replace ListView with RecyclerView in demos

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java

We need a way to restart the downloads workflow in case that it was not already active
A possible scenario: A client denies a download for a particular business rule and that rule does not apply any more. Calling this method will reactivate the downloads workflow, check the client rules and proceed if necessary
A new public method `restart` is provided

Provide restart mechanism

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadReadyChecker.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadTask.java
library/src/main/java/com/novoda/downloadmanager/lib/PublicFacingDownloadMarshaller.java
library/src/test/java/com/novoda/downloadmanager/lib/DownloadReadyCheckerTest.java

When a transfer is on its way, when we write down some transfered bytes we check if the current download has moved to paused or canceled but we do not check if there are client rules that could potentially deny the progress of the current download
The solution is to include the client check along with the current pause and canceled checks
In terms of performance implications:
- New originalDownloadBatch along with the originalDownloadInfo in order to avoid the creation of the former when there is a bunch of bytes transferred on write
- Exposed packaged protected the method that checks the client rules in order to avoid the overhead of checking the internals of the download manager, specially the unnecessary query for all downloads

Add client checks along with pause and cancel checks and speed up calls

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadReceiver.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadTask.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/FileDownloadInfo.java

Moves the majority of the status updating to the `*Repository` classes
This is to prepare for simplifying the batch/download statuses in order to fix the flickering status issue

Status updating refactoring

---

library/src/main/java/com/novoda/downloadmanager/lib/Constants.java
library/src/main/java/com/novoda/downloadmanager/lib/TarTruncator.java
library/src/test/java/com/novoda/downloadmanager/lib/TarTruncatorTest.java

When using the tar truncator the buffer used for the data transfer is really small (512  bytes) to match the tar format buffer. This allows for the tuncation but creates writes to disk too often.
This uses a double buffer in memory to allow for a buffer of the same size than the original data transfer to be used making sure there is no more writes to disk than needed.
```
Start at 1439216120380
Stop at 1439216120823
Total 443ms
```
```
Start at 1439216197991
Stop at 1439216198146
Total 155ms
```

Use a larger buffer to allow for less often write to disk

---

demo-extended/src/main/AndroidManifest.xml
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/CompletedDownloadsActivity.java
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/MainActivity.java
demo-extended/src/main/res/layout/activity_completed_downloads.xml
demo-extended/src/main/res/layout/activity_main.xml
demo-extended/src/main/res/values/strings.xml
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/Request.java

Previously, you could add a completed download to the DownloadManager database so it could be read. This probably broke when we introduced the batching mechanism as it didn't associate a completed download with a batch.
We needed to be able to add complete *batches* into the download manager, rather than just downloads. This PR adds this functionality, and deprecates the old, unsupported method. We also delegate a few checks which were done manually when they didn't need to be.
This GIF shows the completed download showing up in both the downloads UI and the batches UI.

Add completed batches to DownloadManager

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchTerminationBroadcaster.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadStatus.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadTask.java

The broadcast is only done in case of error. (won't be triggered if a download is cancelled for example)
* Rename the BatchCompletionBroadcaster into BatchTerminationBroadcaster
* extend its API to send a broadcast if a failure occured while downloading.

Add a broadcast for batch failure

---

demo-extended/src/main/AndroidManifest.xml
demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/DownloadBatchStartedReceiver.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchInformationBroadcaster.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadContract.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadTask.java

Need to be able to detect when a batch starts for the first time so that external app can react on this. 
* add a new column to the Batch table, default to zero
* Up the DB version to 2 and handle migration
* when a batch download starts, check the column
* if value is zero, mark batch has started and broadcast an event
* expose the broadcast ACTION so that app using the lib can listen for it

Track batch first time start

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchQuery.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/NotificationDisplayer.java

Title ^
The code modified is inside another `if-else` that says if the download is`TYPE_SUCCESS || TYPE_CANCELLED` then create the notification, but then we would only fire a broadcast event for `SUCCESS`, now we do both.
Before | After
--- | ---

Send broadcast when the download was cancelled as well as successful

---

library/src/main/java/com/novoda/downloadmanager/lib/Constants.java
library/src/main/java/com/novoda/downloadmanager/lib/CursorTranslator.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadBatch.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadReceiver.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadTask.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsUriProvider.java
library/src/main/java/com/novoda/downloadmanager/lib/NotifierWriter.java
library/src/main/java/com/novoda/downloadmanager/lib/PublicFacingDownloadMarshaller.java
library/src/main/java/com/novoda/downloadmanager/lib/PublicFacingStatusTranslator.java
library/src/main/java/com/novoda/downloadmanager/notifications/DownloadNotifier.java
library/src/main/java/com/novoda/downloadmanager/notifications/DownloadNotifierFactory.java
library/src/main/java/com/novoda/downloadmanager/notifications/NotificationDisplayer.java
library/src/main/java/com/novoda/downloadmanager/notifications/SynchronisedDownloadNotifier.java
library/src/test/java/com/novoda/downloadmanager/notifications/DownloadNotifierTest.java

Moves behaviour onto the DownloadBatch so that it is not showing its innards
Moves the actions specifically used for notifications to that package.
Renames status translator to the `PublicFacing` pattern, not ideal but matches other code for now.
Removes unused code.
Creates a factory for the `DownloaNotifier` so that we can create it all in 1 package.
Still more to do, refactoring towards a complete notification package, but this is starting to give our download manager more flexibility.
(merging into https://github.com/novoda/download-manager/pull/162)

Moves more notification code to package

---

library/src/main/java/com/novoda/downloadmanager/notifications/NotificationDisplayer.java
library/src/main/res/values/strings.xml

If the client doesn't provide a description with the request for a download, it used to show a text with the remaining time, the problem being that it could not be changed from the client (from the customiser).
Using a static resource allows us to change it via resource overriding. This is not the ideal solution but it's good enough for now.

Adds a static text for downloading so that it can be overwritten

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadStatus.java
library/src/main/java/com/novoda/downloadmanager/notifications/NotificationDisplayer.java

Title ^
the notifications for a failed download wouldn't fire any intent on click, and they'd reappear after being dismissed every time the DownloadService was recreated.
the click works and they don't reappear after being dismissed
Fixes #51 , #143

Handle failed notifications so that they get dismissed and click events work

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadReceiver.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadStatus.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsUriProvider.java
library/src/main/java/com/novoda/downloadmanager/notifications/DownloadNotifierFactory.java
library/src/main/java/com/novoda/downloadmanager/notifications/NotificationDisplayer.java

We used to have generic actions (inherited from the AOSP) to handle click events - this was confusing and hard to work around it.
We can differentiate between each specific action and handle them all differently if we have to in the `DownloadReceiver`.
Also solved a bug since we were checking for the batch status but it was the translated status instead of the raw one, this was fixed with just using another action :dancer: 
Fixes #161 and #168

Uses multiple actions for click events on notifications so they can be handled differently

---

library/src/main/java/com/novoda/downloadmanager/notifications/NotificationDisplayer.java

We've observed that in some devices (running KitKat) clicking on a downloading notification doesn't fire the `Intent` therefore the `DownloadReceiver` doesn't get notified that the user clicked, resulting on unhandled click events.
After some research it seems like this is a known issue:
https://code.google.com/p/android/issues/detail?id=63236
https://code.google.com/p/android/issues/detail?id=61850
And the workaround is to cancel the PendingIntent and redo it instead of update the existing one.
QA said this works fine now in both KitKat, pre-KitKat and Lollipop devices :boom:

Uses FLAG_CANCEL_CURRENT instead of FLAG_UPDATE_CURRENT for the clicks

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadReceiver.java

This prevents notifications from reappearing when you kill the app after dismissing a notification and start the app again.
- Download something
- When download completes or fails, dismiss the notification by swiping it
- Kill the app
- Start the app again
- The notification would reappear
- No notification reappears

Use the 'HIDDEN' state when hiding a notification

---

library/src/main/java/com/novoda/downloadmanager/notifications/NotificationDisplayer.java

So it turns out the real issue with notifications reappearing after being dismissed was the intents weren't unique. I thought it had to do with the flags we use or the way we handle the notification visibility in the DB, and maybe it did initially but now the problem was the uniqueness of the intents. So the bug could only be reproduced when having multiple failed/completed notifications, with just one it worked fine, that made it harder to pin point.
Anyway this is fixed by making each intent used for the notifications unique as mentioned here http://stackoverflow.com/a/15456633/1180029 and the problem is fixed.
I've done this for both the intent used for dismissing a notification and for the intent used for clicking a notification and it all works fine. See gifs below (the `Before` one …

Makes notifications uniques by setting different data on each of them

---

library/src/main/java/com/novoda/downloadmanager/lib/StorageManager.java

We have noticed that client's content inside the `getCacheDir()` is removed when a download starts
When the download manager instance is instantiated, goes through a process of cleaning up invalid files, calling the method `removeSpuriousFiles` https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/StorageManager.java#L350, this method gets **all** the files inside the `getCacheDir()` and deletes them all (line https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/StorageManager.java#L391)
There is a commented code that tries to discover the process owner of the file in order to prevent this bug but:
- It is commented (the library used is not available and there is an alternative …

Add "download-manager" subdirectory for the used cache dir

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
library/src/main/java/com/novoda/downloadmanager/lib/Request.java

Previously the current size was defaulting to 0 when adding completed downloads, now it uses the total size since the file is already fully downloaded

Sets the current size as the total when adding completed downloads

---

library/src/main/java/com/novoda/downloadmanager/lib/Constants.java
library/src/main/java/com/novoda/downloadmanager/lib/TarTruncator.java
library/src/test/java/com/novoda/downloadmanager/lib/TarTruncatorTest.java

Tar files that are large are usually written as records, that means that we might get padded zeros in writing those chuncks.
That was breaking the truncation logic that was in place.
The new approach is more resilient as it will read by records of 20 blocking factor (default blocking factor of tar) and wait for the end of the stream to try and backtrack within the last read record to find the last block entry before the EOF marker. It will then copy the record up to that point.
This will work for all record size smaller or equal to the default record size of 20.
We could parametrize the blocking factor to make this working with an arbitrary blocking factor.
What do you think ?

Refactor tar truncator to support record based tar files.

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadTask.java

Fixes the bug where downloads were considered successful even though they weren't
The comment says we should have thrown it but looks like it was mistakenly put inside the condition.
Can reproduce this by turning airplane mode on in the middle of a download, and turning it back off so the download resumes. The download will "complete" successfully, but it's not downloaded anymore.

Propagate error upwards instead of swallowing

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java

This is a second try for closed PR #181.
The problem: Currently, DownloadProvider.insertDownload() enforces WRITE_EXTERNAL_STORAGE permission for all downloads using a DESTINATION_FILE_URI, and throws a SecurityException if that permission is missing. However, that permission isn't actually required if the download is destined for internal storage.
The solution: Check to see if the file path begins with Environment.getDataDirectory(). If it does, it's using internal storage and there's no need for WRITE_EXTERNAL_STORAGE permission; therefore, waive enforcement of that permission.
@amlcurran, thanks for the suggestion - I think this will do it.

There's no need to enforce WRITE_EXTERNAL_STORAGE permission for internal downloads. (try #2)

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadTask.java
library/src/main/java/com/novoda/downloadmanager/lib/PublicFacingStatusTranslator.java

In the a previous commit: https://github.com/novoda/download-manager/commit/b6d286a2d052971e0e71935b3ea86839cdec0690 we are now throwing an exception every time an error occurs when transferring data independently if the download is paused, queued, etc, which is right. But know we get "paused" status when is internally "waiting for network".
The download mapper,  was wrong since we were mapping "queued" to "paused" where it needs to be: "pending".
The other problems occurs when the `DownloadService` restarts the downloads when the network resumes after a disconnection. In this case, we are not calling `downloadReadyChecker.canDownload()` method and therefore we are not propagating that "event" to the client.
For the first sub-problem: Fix the mapper.
For the second: Force the downloadTask …

Fix status mapping

---

library/src/main/java/com/novoda/downloadmanager/lib/Request.java

`Uri.toString()` will return something like `"file:///Path/to.file"`, which is incorrect to use as an argument for a `new File()`.  Let me show you this snippet to better express what I mean:
```java
File file1 = new File("file:///data/user/0/com.novoda.downloadmanager.demo.extended/files/Movies/beard.shipment");
File file2 = new File("/data/user/0/com.novoda.downloadmanager.demo.extended/files/Movies/beard.shipment");
file1.exists(); // false
file2.exists(); // true
```
The correct path is the one without the schema prepended, so let's use `Uri.getPath()` instead!
Paired with @zegnus 
Thanks @ouchadam for testing this change on all4.

Use Uri.getPath() instead of .toString() to get destination path

---

library/src/main/java/com/novoda/downloadmanager/lib/Request.java

`Request`s cannot be used in tests because of `android.net.Uri` dependency
I decided to migrate to `java.net.URI` instead, and deprecate the previous constructor and setter.
Thanks @ouchadam for testing again the change on all4 😂

Migrate fields in Request to java.net.URI

---

library/build.gradle

To fix the following build failure:
```
Execution failed for task ':library:mavenAndroidJavadocs'.
> Javadoc generation failed.
```
Although 0.3.5 is the latest version of the plugin, it is known to have the same issue. So we should use 0.3.4

Update bintray release plugin

---

code-quality/android-code-quality.gradle

When doing a maven publication the build fails given some lint warnings / errors in the javadoc of the library. Following a truncated stacktrace for `publishToMavenLocal`:
```
Note: /Users/juankysoriano/Documents/Work/novoda/download-manager/library/src/main/java/com/novoda/downloadmanager/lib/StorageManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:library:mavenAndroidJavadocs
...
/Users/juankysoriano/Documents/Work/novoda/download-manager/library/src/main/java/com/novoda/downloadmanager/lib/Request.java:334: warning: no @param for description
public Request setDescription(CharSequence description) {
^
/Users/juankysoriano/Documents/Work/novoda/download-manager/library/src/main/java/com/novoda/downloadmanager/lib/Request.java:369: …
```

Fix maven publication tasks

---

library/src/main/java/com/novoda/downloadmanager/lib/StorageManager.java

Added null check to verifySpace(int destination, String path, long length)
My last pull request introduced a new bug. It was possible that there is a null File within the array. The new code checks for this.

Fix for StorageManager null bug

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadTask.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/FileDownloadInfo.java

We have spotted two issues:
1. Sometimes when a download is in progress and we lose connection slowly, the full batch is marked as failed. But if we regain connection the download should just continue.
2. When pausing a download, sometimes the batch stays stuck in `queued` mode and the download don't continue. The download should be paused and we should be able to resume it.
1. We have analysed the error status when the batch is marked as failure. There is a connection and the response status code is 404. We have added 404 to the list of retriable statuses and this fixes the issue. All retriable downloads will finally fail after a few trials. This is a one line change fix.
2. The `paused by application` status is checked once every second in order to do not hammer the client at every …

Fix batch failure and locked to pause

---

library/src/main/java/com/novoda/downloadmanager/DatabaseInteraction.java

Fixes #228
We do a check after we've already inserted stuff into the database. If the check fails, we throw an exception.
We should check before dirtying the database instead.

Ensure localFileUri is not a duplicate before inserting to db

---

library/build.gradle

We can't re-use the same version number for two releases.
Increase the version number!

Version number 0.2.46 -> 0.3.0

---

library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java

Hi folks - despite the null check change I submitted in https://github.com/novoda/download-manager/pull/233, the Google Play console is continuing to report lots of app crashes (I think they're actually background service crashes) originating in this class. I inspected it more carefully this time and noted that there are several places in it - not just the one I noted and fixed the first time I looked at it - where cursors might be null but are treated as if they are known to be non-null. This PR is an attempt to address all of those issues.
I'm not sure this is how you would prefer to address some of these. In particular, the method getDownloadFor() seems never to be called in the current codebase, so I just annotated it @Nullable and made it return null in case of a null cursor, but …

Covering all possible null cursor cases in this DownloadsRepository.java

---

app/src/main/java/com/novoda/downloadmanager/demo/DemoApplication.java
library/src/main/java/com/novoda/downloadmanager/DownloadBatchNotification.java
library/src/main/java/com/novoda/downloadmanager/DownloadService.java
library/src/main/java/com/novoda/downloadmanager/LiteDownloadBatchTitle.java
library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
library/src/main/java/com/novoda/downloadmanager/LiteDownloadService.java

We see only a single notification per batch, each notification wipes the previous and we cannot swipe the notification away when the download is completed.
Additionally, when deleting we post a notification that has the current downloaded percentage 😬  since we don't know what we want to do with this we should prevent notification updates when the status is deleted.
Provide a unique id for each notification along with a channel id. When a notification is completed we should remove it from the service (detach) and reattach using the `NotificationManager`. This prevents the new notification from a new batch from wiping the old one. 
- Remove the notification whenever the download status is deleted.
- Stack the notification when the download is completed. This allows another download to show …

Dismiss notification

---

library/src/main/java/com/novoda/downloadmanager/DownloadsNetworkRecoveryCreator.java

If you specify that the `DownloadManager` should not recover from network errors there is a crash 😬  it would be more appropriate to do nothing or allow the client to supply a strategy. 
```
liteDownloadManagerCommands = DownloadManagerBuilder
.newInstance(this, handler, R.mipmap.ic_launcher_round)
.withNetworkDownloader()
.withFilePersistenceInternal()
.withAllowedConnectionType(ConnectionType.UNMETERED)
.withNetworkRecovery(false)
.build();
```
It seems that the `DownloadManager` was always designed to do nothing in the instance where the client requests `withNetworkRecovery(false)` we just weren't assigning to the `INSTANCE` which is why there was a crash.

Network recovery disabled crash

---

library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java
library/src/main/java/com/novoda/downloadmanager/DownloadBatchFactory.java
library/src/main/java/com/novoda/downloadmanager/DownloadBatchStatus.java
library/src/main/java/com/novoda/downloadmanager/DownloadError.java
library/src/main/java/com/novoda/downloadmanager/DownloadFileStatus.java
library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
library/src/main/java/com/novoda/downloadmanager/DownloadsFilePersistence.java
library/src/main/java/com/novoda/downloadmanager/InternalDownloadBatchStatus.java
library/src/main/java/com/novoda/downloadmanager/LiteDownloadBatchStatus.java
library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java

When there is a network error with the first download batch and network recovery is in operation then the second completed batch flickers between `DOWNLOADED` and `QUEUED`.
`DownloadError` is created and passed through the constructor of some objects as `UNKNOWN`. It seems that `UNKNOWN` is used to represent a missing error 🤔  this should instead be an `Optional` or `@Nullable` field.
When queueing downloads ignore all items that are already `DOWNLOADED`. Made `DownloadError` `@Nullable` wherever it is currently used.

Flickering on network recovery

---

library/src/main/java/com/novoda/downloadmanager/SqlDatabaseWrapper.java
library/src/main/java/com/novoda/downloadmanager/VersionOneToVersionTwoMigrator.java

The migration from the v1 database to the v2 database can be stopped at any point if the system runs out of resources. This can currently leave the migration process in an inconsistent state because we process in steps e.g. move files and then move the data.
Perform the migration in batches, where the migration of a batch is performed in a transaction. If the transaction never completes the changes will be rolled back leaving the databases in a consistent state.

Batch by batch migration

---

demo-simple/src/main/java/com/novoda/downloadmanager/demo/CustomNotificationCreator.java
library/src/main/java/com/novoda/downloadmanager/DownloadBatchNotification.java
library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
library/src/main/java/com/novoda/downloadmanager/DownloadNotificationChannelCreator.java
library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
library/src/main/java/com/novoda/downloadmanager/NotificationChannelCreator.java
library/src/main/java/com/novoda/downloadmanager/NotificationCreator.java
library/src/main/java/com/novoda/downloadmanager/Optional.java
library/src/main/res/values/strings.xml

`download-manager` v2 crashes 😱  under the following scenario:
1. Start the demo application
2. Start a download
3. Application crash on API 27, check logs
4. Application does not show a notification on API 26, there is a warning on the usage of the channel
Add a Notification Channel for the standard download notifications that are sent by the `download-manager`.

Android Oreo Notification Channel

---

demo-simple/src/main/java/com/novoda/downloadmanager/demo/CustomNotificationCreator.java
library/src/main/java/com/novoda/downloadmanager/DownloadBatchNotification.java
library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java
library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java
library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrationService.java
library/src/main/java/com/novoda/downloadmanager/MigrationNotification.java
library/src/main/java/com/novoda/downloadmanager/MigrationNotificationChannelCreator.java
library/src/main/java/com/novoda/downloadmanager/MigrationStatus.java
library/src/main/java/com/novoda/downloadmanager/NotificationCreator.java
library/src/main/java/com/novoda/downloadmanager/VersionOneToVersionTwoMigrationStatus.java
library/src/main/res/values/strings.xml

We have a `MigrationService` but it does not supply notifications to the user! 😱 
Implement a `foreground` Service and forward a `MigrationStatus` that will be mapped to a `Notification` and displayed. Decided to open a PR now because I've made some, potentially controversial changes to the `NotificationCreator` interface 😬  I plan to tidy up how we pass information between the `Service` and the `Migrator` in a follow-up PR, possibly by exposing a `MigrationService` interface that can be used to send notifications on `Migrator` progress updates. This would be similar to how the other `Service` works in the library.

Foreground Migration Service

---

library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java

If a client uses any `Context` except the `Application Context` then the app will likely crash because we are leaking the `ServiceConnection`. This occurs because currently the `DLM` does not unbind it 😬 
Ensure that we use only the `Application Context` by calling `context.getApplicationContext` inside the `DLM`.
We should decide how we are going to surface the need to `bind` and `unbind` to the client applications.

Avoid leaking ServiceConnection

---

library/src/main/java/com/novoda/downloadmanager/Migration.java
library/src/main/java/com/novoda/downloadmanager/MigrationJob.java
library/src/main/java/com/novoda/downloadmanager/PartialDownloadMigrationExtractor.java

The new version of the `download-manager` is capable of migrating **complete** downloads from v1 to v2. We also need to be able to migrate **incomplete** downloads, those that do not have a local file path or have a local file path but where the current bytes do not match the total bytes for a batch.
Create a `PartialDownloadMigrationExtractor` that is responsible for extracting a `List<Migration>` that represents just the partial downloads. For partials we check whether the whole batch is downloaded. If the whole batch is not downloaded then we mark it with **queueing** which will automatically trigger a re-download of the files. For the partial downloads that had a local file we delete rather than carrying on from the current byte range. 
If we decide to carry on from a given byte range …

Incomplete downloads

---

demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java
library/src/main/java/com/novoda/downloadmanager/InternalFileSizeCreator.java

When initialising a new `DownloadFile` we use the `UNKNOWN` InternalFileSize. The problem is that _all_ new DownloadFiles used the same instance of InternalFileSize, which was updated with the total size of the first downloaded file, resulting in an inconsistent total batch size.
Use a copy if the constant instance when initialising a new `InternalFileSize`
Show the `%` symbol in the demo activity logs because it was not clear to me that they were referring to the download percentage, at the beginning.

Fix total file size

---

library/src/main/java/com/novoda/downloadmanager/lib/BatchQuery.java
library/src/main/java/com/novoda/downloadmanager/lib/BatchStatusRepository.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadReadyChecker.java
library/src/main/java/com/novoda/downloadmanager/lib/DownloadStatus.java
library/src/main/java/com/novoda/downloadmanager/lib/PublicFacingStatusTranslator.java
library/src/main/java/com/novoda/downloadmanager/lib/Statuses.java
library/src/test/java/com/novoda/downloadmanager/lib/BatchQueryTest.java

When creating a batch with a lot of small download files, we can see that for each file, the batch status goes back to PENDING before going to RUNNING when the current file is actually downloading.
That means that displaying the batch status flickers between Queued and Downloading.
To prevent that effect I have added a BATCH_RUNNING status which means that the batch is running, even if its current download is pending.
Screen capture before the changes:
Before | After
---|---

Batch download status goes back to PENDING between files.
