demo/src/main/java/com/novoda/downloadmanager/demo/Download.java, demo/src/main/java/com/novoda/downloadmanager/demo/DownloadAdapter.java, demo/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java, demo/src/main/java/com/novoda/downloadmanager/demo/QueryForDownloadsAsyncTask.java, demo/src/main/res/layout/activity_main.xml, demo/src/main/res/layout/list_item_download.xml, demo/src/main/res/values/strings.xml
Does what it says on the tin.
Does Query off the main thread.
Uses ASyncTask as this is a demo, simples.
=> Improves demo to show how to query for downloads

demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/DownloadAdapter.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/MainActivity.java, demo-extended/src/main/res/layout/activity_main.xml, demo-extended/src/main/res/layout/list_item_download.xml
- List now refreshes automatically on a change
- Made list items smaller so you can see more
=> Auto-refresh list

demo-extended/src/main/AndroidManifest.xml, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/DemoApplication.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/Download.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/DownloadAdapter.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/MainActivity.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/QueryForDownloadsAsyncTask.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/QueryTimestamp.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchesActivity.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/delete/DeleteActivity.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/pause_resume/PauseResumeActivity.java, demo-extended/src/main/res/layout/activity_batches.xml, demo-extended/src/main/res/layout/activity_delete.xml, demo-extended/src/main/res/layout/activity_main.xml, demo-extended/src/main/res/layout/activity_pause_resume.xml, demo-extended/src/main/res/values/strings.xml
This PR splits the demos into multiple activities (instead of having everything in one).
Main | Pause/Resume | Delete a download | Batch downloads
--- | --- | --- | --- | --- 
Fixes #58
=> Split demos

library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadContract.java
This:
- Removes unused private constant
- Fixes checkstyle ('+' should be at the beginning of the line) for readability
=> Small code improvements

demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/Batch.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchDownloadsActivity.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/BatchesAdapter.java, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/batches/QueryForBatchesAsyncTask.java, demo-extended/src/main/res/layout/list_item_batch.xml, library/src/main/java/com/novoda/downloadmanager/lib/BatchInfo.java, library/src/main/java/com/novoda/downloadmanager/lib/BatchQuery.java, library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java, library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadContract.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java, library/src/main/java/com/novoda/downloadmanager/lib/RequestBatch.java, library/src/test/java/com/novoda/downloadmanager/lib/BatchQueryTest.java, library/src/test/java/com/novoda/downloadmanager/lib/DownloadNotifierTest.java
This PR is very similar to #88 - only difference is it adds the EXTRA_DATA column to the Batches.
=> Add extra column to batches

library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java
Resuming an item would not change its state from paused to resume in UI. This was because we failed to notify a change from the batches URI. 
As another nice thing, we only attempt to resume items which aren't complete, which reduces flickering and reduces the amount of threads we create
=> Fix resumed downloads not being updated in the UI

library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java, library/src/main/java/com/novoda/downloadmanager/lib/NotifierWriter.java, library/src/test/java/com/novoda/downloadmanager/lib/BatchStatusTests.java
Reverts novoda/download-manager#130
Removed all of Ben's TAR code
=> Revert "Fix concurrent downloads and memory leaks"

library/src/main/java/com/novoda/downloadmanager/lib/BatchRepository.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadThread.java, library/src/main/java/com/novoda/downloadmanager/lib/NotifierWriter.java, library/src/test/java/com/novoda/downloadmanager/lib/BatchStatusTests.java
Reverts novoda/download-manager#131
Turns out, it didn't remove Ben's code.
=> Revert "Revert "Fix concurrent downloads and memory leaks""

library/src/main/java/com/novoda/downloadmanager/lib/CheckedWriter.java, library/src/main/java/com/novoda/downloadmanager/lib/DataTransferer.java, library/src/main/java/com/novoda/downloadmanager/lib/DataWriter.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadTask.java, library/src/main/java/com/novoda/downloadmanager/lib/NotifierWriter.java, library/src/main/java/com/novoda/downloadmanager/lib/RegularDataTransferer.java, library/src/main/java/com/novoda/downloadmanager/lib/SizeLimitActivity.java, library/src/main/java/com/novoda/downloadmanager/lib/TarTruncator.java, library/src/test/java/com/novoda/downloadmanager/lib/CheckedWriterTest.java, library/src/test/java/com/novoda/downloadmanager/lib/TarTruncatorTest.java
The download thread object isn't actually a thread, its a Runnable which is submitted to an Executor. I renamed it so that it is more explicit about its role!
=> Rename DownloadThread to DownloadTask

library/src/main/java/com/novoda/downloadmanager/lib/NotificationDisplayer.java
In a situation where we had 2 downloads, one in progress and one cancelled, swiping away the cancelled one didn't hide it permanently.
This was because we weren't adding the hide Intent to cancelled notifications.
This PR adds the hide intent to cancelled notifications and adds some boy scout refactoring.
=> Add hide intent to cancelled downloads

RELEASE-NOTES.md
Release notes didn't mention a PR which was included in the release
=> Add missing line to release notes

library/build.gradle, library/src/main/java/com/novoda/downloadmanager/lib/BatchQuery.java, library/src/main/java/com/novoda/downloadmanager/lib/Criteria.java, library/src/main/java/com/novoda/downloadmanager/lib/DatabaseHelper.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadContract.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java
This PR adds a method to not take into account the batches that have been marked as `DELETED`.
It allows an app to be notified upon deletion right away.
=> Adds a method to exclude deleted batches from query

library/src/main/java/com/novoda/downloadmanager/lib/DownloadReceiver.java
Title ^
#167 fixes the 'failed download' notification reappearing when the user dismisses it but not when the user clicks on it, so this PR fixes that
Also did small boyscouting for the `batchId`
=> If user clicks on a failed download then we want to hide the notification forever

demo-extended/README.md, demo-extended/src/main/java/com/novoda/downloadmanager/demo/extended/DemoApplication.java, library/src/main/java/com/novoda/downloadmanager/lib/DefaultsDownloadManagerModules.java, library/src/main/java/com/novoda/downloadmanager/lib/DestroyListener.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadManagerModules.java, library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java
- This means if anyone makes a module that needs some cleanup before GC, they can do that.
Paired with @hhaouat
=> Add new listener for DownloadManagerModules being released

library/src/main/java/com/novoda/downloadmanager/lib/DownloadService.java, library/src/main/java/com/novoda/downloadmanager/lib/StorageManager.java
I believe I have fixed the build error from my previous submission #203 and fixes issue #201 . I also tried to adjust the formatting to fit the official style. (sorry, I'm manually editing this in Github)
If there are any other issues, I'll do my best to fix them.
=> Allow downloading to location returned from getExternalFilesDirs

library/build.gradle
Upgrade library version to v0.2.45 that includes:
- Downloads reconnect on network disconnections for Android N or greater Restart service on disconnection #213
=> Upgrade library version to v0.2.45

demo-extended/build.gradle, demo-simple/build.gradle, gradle/wrapper/gradle-wrapper.properties, library/build.gradle, library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java, library/src/test/java/com/novoda/downloadmanager/lib/MockCursorWithBatchIds.java, library/src/test/java/com/novoda/downloadmanager/lib/MockCursorWithStatuses.java
Upgrade the following dependencies:
- Gralde from `2.9` to `3.3`
- Gradle plugin from `1.2.3` to `2.3.0`
- Build tools from `22.0.1` to `25.0.2`
- support-v4 from `22.2.1` to `25.3.0`
Compile target from `22` to `25`
=> Upgrade dependencies

library/build.gradle
Update library version to v0.2.46 with the aim of #230.
=> Update to v0.2.46

library/src/main/java/com/novoda/downloadmanager/lib/DownloadsRepository.java
Hi folks,
Submitting a fix (I'm pretty sure - I can't actually repro but the stack trace is pretty clear) for an issue that's been causing a considerable number of crashes in our apps). Thanks for your consideration. (Also, sorry for the false start a bit earlier when I submitted a PR from my company's repo - I need to use *that* fork as the actual library for our apps until/unless this gets merged in, so I want to keep it separate from this PR.)
Thanks again,
Mike Croghan
=> Null check on downloadsCursor

app/src/main/java/com/novoda/downloadmanager/demo/DemoApplication.java, library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java, library/src/main/java/com/novoda/downloadmanager/InternalDownloadBatchStatus.java, library/src/main/java/com/novoda/downloadmanager/LiteDownloadBatchStatus.java
When a download is completed and transitions to the DOWNLOADED state in the UI the database is not updated to reflect this change 🤔 
Mark a `downloadBatch` as complete and update the `db`.
=> No downloaded status

library/src/main/java/com/novoda/downloadmanager/CallbackThrottleCreator.java, library/src/test/java/com/novoda/downloadmanager/CallbackThrottleCreatorTest.java, library/src/test/java/com/novoda/downloadmanager/TestNonInstantiableCustomThrottle.java, library/src/test/java/com/novoda/downloadmanager/TestNonPublicCustomThrottle.java, library/src/test/java/com/novoda/downloadmanager/TestValidCustomThrottle.java
Just adding tests for the `CallbackThrottleCreator` 😄
=> Add tests for CallbackThrottleCreator

library/src/main/java/com/novoda/downloadmanager/DownloadManager.java, library/src/test/java/com/novoda/downloadmanager/DownloadManagerTest.java
Add tests to the `DownloadManager` class. Opening for a head-start on reviews 😄  there will be some tidy up on these tests.  Does anyone have ideas on how to test the synchronized blocks in this class?
=> Add tests for the DownloadManager

library/src/test/java/com/novoda/downloadmanager/NetworkFileDownloaderTest.java, library/src/test/java/com/novoda/downloadmanager/NetworkResponseFixtures.java
Add tests for the `NetworkFileDownloader`
=> File downloader tests

library/src/main/java/com/novoda/downloadmanager/LiteFileSize.java, library/src/test/java/com/novoda/downloadmanager/NetworkFileSizeRequesterTest.java
Adds tests for the `NetworkFileSizeRequester`. Adds `equals` and `hashcode` to `LiteFileSize`
=> Add tests for the file size requester.

build.gradle, demo-simple/build.gradle, gradle/wrapper/gradle-wrapper.properties, library/build.gradle
The versions of Gradle and the Android Gradle plugin being used to build the library and demo app were out of date.
This pull request is to update them to the latest available.
I also updated other dependencies at the same time.
=> Update dependencies, including Gradle, Android Gradle plugin, support libraries

demo-simple/src/main/java/com/novoda/downloadmanager/demo/DatabaseClonerFactory.java, demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java, demo-simple/src/main/java/com/novoda/downloadmanager/demo/VersionOneDatabaseCloner.java, demo-simple/src/main/res/layout/activity_main.xml, demo-simple/src/main/res/values/strings.xml
We want to be able to change the file size when cloning the v1 database.
Add a spinner option to select from a series of download file sizes.
=> File size spinner

demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java, library/src/main/java/com/novoda/downloadmanager/InternalMigrationStatus.java, library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrationService.java, library/src/main/java/com/novoda/downloadmanager/MigrationFactory.java, library/src/main/java/com/novoda/downloadmanager/MigrationNotification.java, library/src/main/java/com/novoda/downloadmanager/MigrationService.java, library/src/main/java/com/novoda/downloadmanager/MigrationStatus.java, library/src/main/java/com/novoda/downloadmanager/Migrator.java, library/src/main/java/com/novoda/downloadmanager/NotificationCreator.java, library/src/main/java/com/novoda/downloadmanager/VersionOneToVersionTwoMigrationStatus.java, library/src/main/java/com/novoda/downloadmanager/VersionOneToVersionTwoMigrator.java
Created a foreground migration service in #273 but the notifications do not sure progress updates etc. 
Create a `MigrationStatus` that encapsulates all of the information necessary to be able to create notifications with progress updates.
=> MigrationStatus progress notifications

demo-simple/build.gradle, demo-simple/src/main/java/com/novoda/downloadmanager/demo/DatabaseClonerFactory.java, demo-simple/src/main/java/com/novoda/downloadmanager/demo/MainActivity.java, demo-simple/src/main/java/com/novoda/downloadmanager/demo/VersionOneDatabaseCloner.java, library/build.gradle, library/src/main/java/com/novoda/downloadmanager/DownloadBatch.java, library/src/main/java/com/novoda/downloadmanager/DownloadBatchFactory.java, library/src/main/java/com/novoda/downloadmanager/DownloadManager.java, library/src/main/java/com/novoda/downloadmanager/DownloadManagerBuilder.java, library/src/main/java/com/novoda/downloadmanager/DownloadsBatchPersistence.java, library/src/main/java/com/novoda/downloadmanager/FileOperations.java, library/src/main/java/com/novoda/downloadmanager/FilePersistenceResult.java, library/src/main/java/com/novoda/downloadmanager/LiteDownloadManagerDownloader.java, library/src/main/java/com/novoda/downloadmanager/LiteDownloadMigrator.java, library/src/main/java/com/novoda/downloadmanager/LiteDownloadService.java, library/src/main/java/com/novoda/downloadmanager/LiteJobDownload.java, library/src/main/java/com/novoda/downloadmanager/NetworkRequestCreator.java, library/src/main/java/com/novoda/downloadmanager/SchedulerFactory.java, library/src/main/java/com/novoda/downloadmanager/WaitForLockRunnable.java, library/src/test/java/com/novoda/downloadmanager/DownloadManagerTest.java
Too much boiler plate.
Use Java 8 and leverage lambdas.
@danybony
=> Use java 8
